### ISSUE TITLE
The full answer is provided in the lib/tic_tac_toe.rb directory

### ISSUE THREAD

**Issue by astania** [learn-co-curriculum/phase-3-oo-tic-tac-toe#1]
Maybe I'm mistaken and it's supposed to be this way, but the while TicTacToe class with all the class methods are provided when you open the tic_tac_toe.rb directory.

**Comment by professor-ben** [comment]
Thanks for letting us know! There was an unintentional merge a couple of weeks ago that combined the solution branch with master. That change has been reverted.
